services:
  jobportal-db:
    image: postgres:16.3-bullseye
    container_name: jobportal-db
    ports:
      - "4443:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - jobportal-db-data:/var/lib/postgresql/data
    networks:
      - jobportal-net
volumes:
  jobportal-db-data:

networks:
  jobportal-net:
    driver: bridge