spring.application.name=job-portal

#config profile
spring.profiles.active=dev

#config Spring Data JPA
spring.jpa.hibernate.ddl-auto=update

#config datasource
spring.datasource.driver-class-name=org.postgresql.Driver

#config mail server
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB